# ---
# name: Build and Release

# on:
#   push:
#     tags:
#       - 'v*'

# jobs:
#   release:
#     name: Build and Release Binaries
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Go
#         uses: actions/setup-go@v5
#         with:
#           go-version: '1.23'

#       - name: Build for macOS & Linux
#         run: |
#           mkdir dist
#           GOOS=darwin GOARCH=amd64 go build -o dist/myapp-mac-intel
#           GOOS=darwin GOARCH=arm64 go build -o dist/myapp-mac-arm
#           GOOS=linux GOARCH=amd64 go build -o dist/myapp-linux-amd64
#           GOOS=linux GOARCH=arm64 go build -o dist/myapp-linux-arm64

#       - name: Create GitHub Release
#         uses: softprops/action-gh-release@v2
#         with:
#           files: dist/*
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
